_target_: lightning.pytorch.trainer.Trainer
default_root_dir: ${paths.output_dir}
min_epochs: 1 
max_epochs: 2
val_check_interval: 20
deterministic: False
accelerator: gpu
devices: 0,1
strategy: fsdp
accumulate_grad_batches: 4
precision: 16
